### ISSUE TITLE
有中文版epub吗？

### ISSUE THREAD

**Issue by AniOSDeveloper** [iosre/iOSAppReverseEngineering#6]
如题，无论如何，还是非常赞赏开源！！！

**Comment by iosre** [comment]
[有](http://static.amazon.cn/iOS%E5%BA%94%E7%94%A8%E9%80%86%E5%90%91%E5%B7%A5%E7%A8%8B-%E6%B2%99%E6%A2%93%E7%A4%BE-%E5%90%B4%E8%88%AA-%E8%91%97/dp/B00V32OY6U)
